# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/leonrinkel/microlinux/microlinux.srcs/sources_1/bd/microlinux_1/ip/microlinux_1_microblaze_0_axi_intc_0/microlinux_1_microblaze_0_axi_intc_0.xci
# IP: The module: 'microlinux_1_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/leonrinkel/microlinux/microlinux.gen/sources_1/bd/microlinux_1/ip/microlinux_1_microblaze_0_axi_intc_0/microlinux_1_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microlinux_1_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/leonrinkel/microlinux/microlinux.gen/sources_1/bd/microlinux_1/ip/microlinux_1_microblaze_0_axi_intc_0/microlinux_1_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'microlinux_1_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/leonrinkel/microlinux/microlinux.gen/sources_1/bd/microlinux_1/ip/microlinux_1_microblaze_0_axi_intc_0/microlinux_1_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microlinux_1_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/leonrinkel/microlinux/microlinux.srcs/sources_1/bd/microlinux_1/ip/microlinux_1_microblaze_0_axi_intc_0/microlinux_1_microblaze_0_axi_intc_0.xci
# IP: The module: 'microlinux_1_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/leonrinkel/microlinux/microlinux.gen/sources_1/bd/microlinux_1/ip/microlinux_1_microblaze_0_axi_intc_0/microlinux_1_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microlinux_1_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/leonrinkel/microlinux/microlinux.gen/sources_1/bd/microlinux_1/ip/microlinux_1_microblaze_0_axi_intc_0/microlinux_1_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'microlinux_1_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/leonrinkel/microlinux/microlinux.gen/sources_1/bd/microlinux_1/ip/microlinux_1_microblaze_0_axi_intc_0/microlinux_1_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microlinux_1_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
