# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Arty-A7-100-Master.xdc

# Block Designs: bd/microlinux_1/microlinux_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1 || ORIG_REF_NAME==microlinux_1} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_clk_wiz_0_0/microlinux_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_clk_wiz_0_0 || ORIG_REF_NAME==microlinux_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_mig_7series_0_0/microlinux_1_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_mig_7series_0_0 || ORIG_REF_NAME==microlinux_1_mig_7series_0_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_microblaze_0_0/microlinux_1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_microblaze_0_0 || ORIG_REF_NAME==microlinux_1_microblaze_0_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_dlmb_v10_0/microlinux_1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_dlmb_v10_0 || ORIG_REF_NAME==microlinux_1_dlmb_v10_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_ilmb_v10_0/microlinux_1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_ilmb_v10_0 || ORIG_REF_NAME==microlinux_1_ilmb_v10_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_dlmb_bram_if_cntlr_0/microlinux_1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==microlinux_1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_ilmb_bram_if_cntlr_0/microlinux_1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==microlinux_1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_lmb_bram_0/microlinux_1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_lmb_bram_0 || ORIG_REF_NAME==microlinux_1_lmb_bram_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_xbar_0/microlinux_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_xbar_0 || ORIG_REF_NAME==microlinux_1_xbar_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_microblaze_0_axi_periph_0/microlinux_1_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==microlinux_1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_microblaze_0_axi_intc_0/microlinux_1_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==microlinux_1_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_microblaze_0_xlconcat_0/microlinux_1_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_microblaze_0_xlconcat_0 || ORIG_REF_NAME==microlinux_1_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_mdm_1_0/microlinux_1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_mdm_1_0 || ORIG_REF_NAME==microlinux_1_mdm_1_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_rst_mig_7series_0_83M_0/microlinux_1_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==microlinux_1_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_axi_ethernetlite_0_0/microlinux_1_axi_ethernetlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_axi_ethernetlite_0_0 || ORIG_REF_NAME==microlinux_1_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_axi_quad_spi_0_0/microlinux_1_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_axi_quad_spi_0_0 || ORIG_REF_NAME==microlinux_1_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_axi_uartlite_0_0/microlinux_1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_axi_uartlite_0_0 || ORIG_REF_NAME==microlinux_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_axi_timer_0_0/microlinux_1_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_axi_timer_0_0 || ORIG_REF_NAME==microlinux_1_axi_timer_0_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_ssd_0_0/microlinux_1_ssd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_ssd_0_0 || ORIG_REF_NAME==microlinux_1_ssd_0_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_xlconcat_0_0/microlinux_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_xlconcat_0_0 || ORIG_REF_NAME==microlinux_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_xlconcat_1_0/microlinux_1_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_xlconcat_1_0 || ORIG_REF_NAME==microlinux_1_xlconcat_1_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_xlconstant_0_0/microlinux_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_xlconstant_0_0 || ORIG_REF_NAME==microlinux_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_pc_6/microlinux_1_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_pc_6 || ORIG_REF_NAME==microlinux_1_auto_pc_6} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_us_0/microlinux_1_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_us_0 || ORIG_REF_NAME==microlinux_1_auto_us_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_us_1/microlinux_1_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_us_1 || ORIG_REF_NAME==microlinux_1_auto_us_1} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_us_2/microlinux_1_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_us_2 || ORIG_REF_NAME==microlinux_1_auto_us_2} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_ds_0/microlinux_1_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_ds_0 || ORIG_REF_NAME==microlinux_1_auto_ds_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_pc_0/microlinux_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_pc_0 || ORIG_REF_NAME==microlinux_1_auto_pc_0} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_ds_1/microlinux_1_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_ds_1 || ORIG_REF_NAME==microlinux_1_auto_ds_1} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_pc_1/microlinux_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_pc_1 || ORIG_REF_NAME==microlinux_1_auto_pc_1} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_ds_2/microlinux_1_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_ds_2 || ORIG_REF_NAME==microlinux_1_auto_ds_2} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_pc_2/microlinux_1_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_pc_2 || ORIG_REF_NAME==microlinux_1_auto_pc_2} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_ds_3/microlinux_1_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_ds_3 || ORIG_REF_NAME==microlinux_1_auto_ds_3} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_pc_3/microlinux_1_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_pc_3 || ORIG_REF_NAME==microlinux_1_auto_pc_3} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_ds_4/microlinux_1_auto_ds_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_ds_4 || ORIG_REF_NAME==microlinux_1_auto_ds_4} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_pc_4/microlinux_1_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_pc_4 || ORIG_REF_NAME==microlinux_1_auto_pc_4} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_ds_5/microlinux_1_auto_ds_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_ds_5 || ORIG_REF_NAME==microlinux_1_auto_ds_5} -quiet] -quiet

# IP: bd/microlinux_1/ip/microlinux_1_auto_pc_5/microlinux_1_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microlinux_1_auto_pc_5 || ORIG_REF_NAME==microlinux_1_auto_pc_5} -quiet] -quiet

# XDC: /home/leonrinkel/microlinux/microlinux.gen/sources_1/bd/microlinux_1/microlinux_1_ooc.xdc
